### PR TITLE
Address betanet chain ID

### LINKED ISSUE #71: Incorrectly reports BetaNet as MainNet
When testing the EVM deployed to the betanet, [near-eth-rpc](https://github.com/near/near-eth-rpc) returns:

```bash
$ http --ignore-stdin post http://localhost:8545 jsonrpc=2.0 id=1 method=net_version params:='[]'
{"jsonrpc":"2.0","id":"1","result":"1313161554"} 
```

That's the [chain ID](https://chainid.network) for MainNet, not BetaNet. The cause of the bug is clear enough:

https://github.com/near/near-web3-provider/blob/ed2243ca272b01946f0398552e25edd44e8e2115/src/index.js#L105-L107

https://github.com/near/near-web3-provider/blob/ed2243ca272b01946f0398552e25edd44e8e2115/src/index.js#L23-L25

Related issue: https://github.com/near/nearcore/issues/3781

### PR DESCRIPTION
**Pull request by mikedotexe**
Fairly simple PR, now that betanet has its own chain ID as shown here:
https://chainid.network

Moved some logic into the network configuration instead of during instantiation of the class.

Fixes #71

### CODE REVIEW

File: src/network-config.js [hunk 1]
```diff
@@ -15,6 +18,7 @@ const getNetworkConfig = function getNetworkConfig(networkId) {
                 evmAccountId: 'evm',
                 walletUrl: 'https://wallet.testnet.near.org',
                 explorerUrl: 'https://explorer.testnet.near.org',
+                version: consts.NEAR_NET_VERSION_TEST
```
Comment (artob) [inline src/network-config.js:21]: Probably would make sense to rename this constant to `NEAR_NET_VERSION_TESTNET` going forward.

**Review by artob — APPROVED** [review]
LGTM :+1:
